### ISSUE TITLE
Issue with FireFox

### ISSUE THREAD

**Issue by coreyha** [bediniupi/Alma-print-slip#1]
FireFox only print the first page. It works fine with Chrome.

**Comment by bediniupi** [comment]
It's a firefox bug: when an element contains a "display: flex" css rule the printing doesn't break pages correctly: this rule is applied in the receipt's div element "#slip_flex", because in this way I can use the "order" css property to reorder the receipt sections.

As workaround you can add this line to signature css (the last one) in the Alma Slip Print addon configuration:
"} #slip_flex { display: block; }"
So if the css signature is a line like:
"Signature: order: 5; padding-top:50px;"
this becomes:
"Signature: order: 5; padding-top:50px;} #slip_flex { display: block; }"
Obviously in this way you cannot reorder the elements by css anymore.

I suggest you to use the new bookmarklet version: https://github.com/bediniupi/Alma-Print-slip-bookmarklet
This way is simplier and you can reorder elements without flex rules, so even long loans receipt will be printed in firefox correctly.
